[[plugins]]
repo = 'Shougo/dein.vim'

# git clone 後、コマンドを実行する
[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  let g:dein#plugin.build = 'make'
'''

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'Shougo/vimshell.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'chriskempson/vim-tomorrow-theme' 

[[plugins]]
repo = 'itchyny/lightline.vim'

# html, css, javascript
[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'gko/vim-coloresque'

# 特定のファイルタイプで読み込む
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'kannokanno/previm''
on_ft = ['markdown']

[[plugins]]
repo = 'tyru/open-browser.vim''
on_ft = ['markdown']

# インサートモードに入ったら読み込む
[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

[[plugins]]
repo   = 'Shougo/unite.vim'

# unite.vim を読み込んだら一緒に読み込む
[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']
